sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hk123456..
  alioss:
    access-key-id: your_access_key_id
    access-key-secret: your_access_key_secret
    bucket-name: lr1descent-sky
    endpoint: oss-cn-hangzhou.aliyuncs.com
