sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hk123456..
  alioss:
    access-key-id: LTAI5tMVc9uej6rF1nWayQMe
    access-key-secret: 0sXZ3ESegBCOqYaD938QKwwapKIPH8
    bucket-name: lr1descent-sky
    endpoint: oss-cn-hangzhou.aliyuncs.com
